# Generated by Django 4.2.25 on 2025-11-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_invoice_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notes_file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('notes_file', models.FileField(blank=True, null=True, upload_to='course_notes/')),
                ('session_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of session in course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
