# Generated by Django 4.2.25 on 2025-11-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_course_notes_file_remove_course_videos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesession',
            options={},
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='notes_file',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='order',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='video_file',
        ),
        migrations.AddField(
            model_name='coursesession',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='sessions/pdfs/'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sessions/videos/'),
        ),
    ]
