# Generated by Django 5.2.8 on 2026-10-05 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_coursesession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='coursesession',
            options={'ordering': ['order', 'id'], 'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسات'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_time'], 'verbose_name': 'ثبت\u200cنام / فاکتور', 'verbose_name_plural': 'ثبت\u200cنام\u200cها / فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='coursesession',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='پیش\u200cنمایش رایگان'),
        ),
        migrations.AddField(
            model_name='coursesession',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='مبلغ (تومان)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدت (ساعت)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آزمون'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سطح'),
        ),
        migrations.AlterField(
            model_name='course',
            name='limit_students',
            field=models.IntegerField(blank=True, null=True, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='course_logos/', verbose_name='تصویر دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='میانگین امتیاز'),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='پیش\u200cنیازها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='sessions/pdfs/', verbose_name='جزوه (PDF)'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sessions/videos/', verbose_name='ویدیو'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='نتیجه'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='تصویر پروفایل'),
        ),
    ]
