# Generated by Django 5.2.8 on 2026-10-05 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_partner'),
        ('users', '0005_persian_labels_teacher_approval_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'ادمین', 'verbose_name_plural': 'ادمین\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['priority'], 'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order_index', '-uploaded_at'], 'verbose_name': 'تصویر گالری', 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'همکار', 'verbose_name_plural': 'همکاران'},
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.course', verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'سطح ۱ - گالری'), (2, 'سطح ۲'), (3, 'سطح ۳'), (4, 'سطح ۴ - مدیریت محتوا و دوره\u200cها'), (5, 'مدیر کل')], default=1, verbose_name='سطح دسترسی'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='activity_history',
            field=models.TextField(blank=True, null=True, verbose_name='سابقه فعالیت'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='register_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان نمایش'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع نمایش'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_comments', to=settings.AUTH_USER_MODEL, verbose_name='درباره کاربر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ رویداد'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک تصویر (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر شده'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='order_index',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.CharField(blank=True, help_text='با کاما جدا کنید', max_length=255, verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_galleries', to=settings.AUTH_USER_MODEL, verbose_name='آپلود کننده'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partners/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
